namespace TheReplacement.PokemonDamageCalc.Constants
{
    public static class Moves
    {
        public const string
            BodyPress = "body-press",
            BodySlam = "body-slam",
            CollisionCourse = "collision-course",
            DoomDesire = "doom-desire",
            DragonRage = "dragon-rage",
            DragonRush = "dragon-rush",
            Earthquake = "earthquake",
            ElectroBall = "electro-ball",
            ElectroDrift = "electro-drift",
            Facade = "facade",
            Feint = "feint",
            FoulPlay = "foul-play",
            Frustation = "frustration",
            FutureSight = "future-sight",
            Gust = "gust",
            GyroBall = "gyro-ball",
            HeatCrash = "heat-crash",
            HeavySlam = "heavy-slam",
            Hurricane = "hurricane",
            HydroSteam = "hydro-steam",
            HyperDrill = "hyper-drill",
            HyperspaceFury = "hyperspace-fury",
            HyperspaceHole = "hyperspace-hole",
            FlyingPress = "flying-press",
            Magnitude = "magnitude",
            MightyCleave = "mighty-cleave",
            NightShade = "night-shade",
            PhantomForce = "phantom-force",
            Psyblade = "psyblade",
            Psyshock = "psyshock",
            Psystrike = "psystrike",
            Return = "return",
            SacredSword = "sacred-sword",
            SecretSword = "secret-sword",
            SeismicToss = "seismic-toss",
            ShadowForce = "shadow-force",
            SkyUppercut = "sky-uppercut",
            SmackDown = "smack-down",
            SpectralThief = "spectral-thief",
            SonicBoom = "sonic-boom",
            Stomp = "stomp",
            SupercellSlam = "supercell-slam",
            Surf = "surf",
            ThousandArrows = "thousands-arrows",
            Thunder = "thunder",
            Twister = "twister",
            Whirlpool = "whirlpool";
    }
}
